### PR TITLE
Added methods for resources, permissions, scopes, policies (Auth service)

### PR DESCRIPTION
**Pull request by vinh-thieu**
Added more endpoints for Authorization Service:
- List resources: `GET {id}/authz/resource-server/resource`
- Create resource: `POST {id}/authz/resource-server/resource`
- Delete resource: `DELETE /{id}/authz/resource-server/resource/{resourceId}`
- List policies: `GET {id}/authz/resource-server/policy`
- List all scopes: `GET /{id}/authz/resource-server/scope`
- Find permission: `GET {id}/authz/resource-server/permission`

### CODE REVIEW

**Comment by justphil86** [comment]
I would love to have this functionality released very soon, I need to list and create resources. :+1:

**Comment by justphil86** [comment]
@vinh-thieu I tested your commit and it works like a charm, thank you. Again, this should be merged as it's a major improvement for this project. :)

**Comment by LRipi** [comment]
Hi @edewit, 
Do you think that improvement will be available in the next releases? 😄

**Comment by LRipi** [comment]
@vinh-thieu It would be great to add the evaluation endpoint! 
The endpoint is: `POST {id}/authz/resource-server/policy/evaluate`

If you want I can contribute to this feature!

**Comment by edewit** [comment]
@vinh-thieu thanks this will be very helpful

**Pull request merged**
