### PR TITLE
Permissions group

### PR DESCRIPTION
**Pull request by KyDenZ**
In addition to the pull request https://github.com/keycloak/keycloak-nodejs-admin-client/pull/46 we could add permissions in groups. I am containing duplicates compared to what has already been done in this pull request, but it was to make it work on my side.

- Enable permissions for a group
- User policy management
- Update scope permissions

### CODE REVIEW

**Comment by zagaria** [comment]
Hi @KyDenZ

Thanks for contributing, but can you, please, prepare code with all passed tests?

Thanks.

**Comment by KyDenZ** [comment]
> Thanks for contributing, but can you, please, prepare code with all passed tests?

Hi @zagaria,
Yes of course I was waiting for the pull request Authorization management to be merged.

**Comment by KyDenZ** [comment]
Hey @zagaria any updates on this one?

**Comment by remixedrewired** [comment]
> Hey @zagaria any updates on this one?

Hello there @zagaria! I am also interested, whether this update of @KyDenZ will be merged?

**Comment by nicolashorbacz** [comment]
Can someone check this pull request ?

**Pull request merged**
