### PR TITLE
Required actions + Authorization management

### PR DESCRIPTION
**Pull request by milicadjordjevic**
Added features:
* Users management permissions
* Authentication Management: Required actions
* Authorization: Permission and Policy Management

### CODE REVIEW

**Comment by zagaria** [comment]
Hi @milicadjordjevic!

Thanks for contributing! I will review tomorrow.

**Comment by zagaria** [comment]
Hi @milicadjordjevic. 

Did you review the comments for review? If yes - can you, please, put answers? Thanks.

**Comment by backbone87** [comment]
i dont see any comments in this PR?

**Comment by milicadjordjevic** [comment]
> Hi @milicadjordjevic.
> 
> Did you review the comments for review? If yes - can you, please, put answers? Thanks.

Hi @zagaria,
I've been following this PR, but I haven't seen any comments/reviews. Can you double check that you still see your review or what is the reason that I can't see it? 
I will gladly participate in the review and would like to have this features released.

**Comment by zagaria** [comment]
@milicadjordjevic  
зображення

**Comment by milicadjordjevic** [comment]
@zagaria 
I assume that the reason why I can't see it is because those comments are in state "pending". 
"Before you submit your review, your line comments are pending and only visible to you. " (https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/reviewing-proposed-changes-in-a-pull-request).

Regarding the definition of policyRepresentation: yes, you are right, in the Keycloak REST API documentation, policyRepresentation doesn't have groups field. The thing is that some of the authorization services endpoints are not documented there (possibly because they are part of the Fine grain permissions feature that is not fully supported - https://www.keycloak.org/docs/latest/server_admin/#_fine_grain_permissions), although they are clearly accessible to use through the API and Admin console UI. Creating group policies are documented here: https://www.keycloak.org/docs/latest/authorization_services/#_policy_group. So, according to Admin console UI functionalities and this "Authorization services" part of documentation I made this functionality that has optional field groups for policies if we are trying to create policy of type group.

Do you have some suggestion on how we can handle this better or any other comments?

**Comment by zagaria** [comment]
@milicadjordjevic thanks for catch! I will review this.

**Comment by zagaria** [comment]
@milicadjordjevic based that this functionality is in preview mode, not documented and can be unstable, it can't be merged to master branch. But anyway, if you need this functionality - I can split on two branches: master and preview. In this case will have 2 releases - stable and preview.

**Comment by milicadjordjevic** [comment]
@zagaria 
It's reasonable to split it in two releases as you suggested. The only thing that concerns me is that in the PR, among this autorization feature that is in preview mode, there are also: "Users management permissions" and "Authentication Management: Required actions" that are actually documented. 
So, what was your idea: to put all in the preview branch/release or to somehow separate those two other things that are documented?

**Comment by milicadjordjevic** [comment]
FYI: I also posted on Keycloak developer mailing list, asking about plans for the Fine grain permissions:
https://groups.google.com/forum/#!topic/keycloak-dev/CgF8ZuNqVRg

**Comment by zagaria** [comment]
@milicadjordjevic can you, please, prepare a new pull request without preview features for master branch?

Thanks.

**Comment by milicadjordjevic** [comment]
@zagaria 
Great, thanks for merging this. Is it now released or when can I expect it to be released? If yes, please let me know how to use it (I tried with @preview tag). 

Sure, I will prepare new PR without preview features for master branch.

**Pull request merged**
