### PR TITLE
fix when global not defined

### PR DESCRIPTION
**Pull request by edewit**
fixes: #120

@volkflo can you give it a try?

### CODE REVIEW

**Comment by volkflo** [comment]
Cool, I will try this asap

**Comment by volkflo** [comment]
This is not working because `global` is still `undefined` first.
See:
image

This should solve it:
`const globalObject = typeof global !== "undefined" ? global as any : {};`

**Comment by edewit** [comment]
just seems to me like a more complex version of writing `const globalObject = global || {};`, but I guess the problem is that your build uses the typescript to make assumptions on the object being there or not.

**Comment by svzieg** [comment]
Hi @edewit,  
in vanilla-js every *not defined* variable will throw an `ReferenceError`. You also can test this behaviour by opening your browser console and type `global` in it. Even nodejs will throw an error for yet not defined variables. The main problem is, that nodejs defines a `global` variable, while vanilla-js doesn't. Therefore, unless you define a variable called `global` in js (or ts) the interpreter will throw an error when executing.

You either have to: 
* define a variable via `var`, `let` at some point (no value is fine). Then the interpreter will return `undefined`.
* or use a `try-catch` construct as described by the [mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError)

**Comment by volkflo** [comment]
@edewit Is it possible to merge this and create a patch release? :)

**Comment by edewit** [comment]
@volkflo release version 1.14.5

**Comment by volkflo** [comment]
Thank you for this release!

**Pull request merged**
