### PR TITLE
User sessions/consents/logout and realm-events

### PR DESCRIPTION
**Pull request by gerdsander**
Hi,

because we need session handling for users I added the neccessary methods at users resource as well as a UserSessionRepresentation.
Also we have to fetch filtered events form keycloak for a realm. This functionallity is added to realms resource. An EventsRepresentation is the result object. For strongly typed query-filter I added EventType enum.

Please look at the changes and I hope you'll merge.

Regards Gerd

### CODE REVIEW

**Comment by zagaria** [comment]
Hello. Sorry for the delay.

Questions:
1. What the linter are you using? Because in some of the files just added additional spaces.
2. Why split on own eventType.ts? Why not as a part of eventRepresentation.ts?

**Comment by gerdsander** [comment]
Hello,

no problem if you've been too busy ;-)

I use VSCode and got
> tslint --version
5.3.2
So I don't know why there are extra spaces. May be it's because I am on windows 10?

I split this to export the enum as default interface so I can use imports as with the normal interfaces. But we can change this if you think using it as part of eventRepresentationts. would be better.

**Comment by gstester** [comment]
Hello,

as I have to keep working on the admin client, should I use a new pull request then?
What's about this one?

**Comment by justintime4tea** [comment]
That's tslint / vscode putting in the spaces in-between brackets. I particularly like it but to stop it you'll need to do a couple tweaks to either your workspace settings or user settings as well as tslint configuration. I believe that's a pretty widely accepted thing to do (spaces before/after non-empty brackets) but it would look odd amid a project that does the exact opposite mostly everywhere else.

**Comment by gstester** [comment]
Hi Justin, 
I removed spaces before brackets.

What about the eventTypes enumeration, you mentioned?

And my whish to enhance the lib to support some other functions?

All the best Gerd

**Comment by justintime4tea** [comment]
Hi Gerd,
I was only making comment that there are some TSLint settings which can help you enforce style like that so you don't have to manually remove them (or add them), glad you were able to update the style to match the projects.

I don't recall mentioning eventTypes enumeration (maybe on another issue?) but I too want (need?) user session information and so hopefully any remaining issues with your PR can be settled and we can gain this and your other functionality in this project.

**Comment by wwwy3y3** [comment]
hi all, 

Sorry I couldn't put much time on this project due to heavy work load from my company lately.

I've added @zagaria as maintainer of this repo, since he already helped us a lot on PR review and contribution.

From this day, @zagaria will also have permission to merge PR and push commits.

Thanks @zagaria again for reaching me out and offer to help out.

**Comment by gp187** [comment]
Ready to merge? Currently using HTTP refresh token workaround and we have tons of unused sessions we can't clear

**Comment by zagaria** [comment]
Hello @gp187. I will check CI (because had problem) and after fix, I think, code can be merged.

**Comment by gerdsander** [comment]
Thx

Am 18. September 2019 18:43:17 schrieb Alex <notifications@github.com>:
> Hello @gp187. I will check CI (because had problem) and after fix, I think, 
> code can be merged.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


Mit AquaMail Android
https://www.mobisystems.com/aqua-mail

**Pull request merged**
