### PR TITLE
Add a remove session

### PR DESCRIPTION
**Pull request by ogaston**
Hi folks,

First off, thank you for this amazing tool.

I'd like to include the removeSession method that allows us to remove an user session by its id.

Any suggestion?

### CODE REVIEW

**Comment by edewit** [comment]
@ogaston cool thanks, could you add a test case for it as well?

**Comment by ogaston** [comment]
Hi @edewit,

I'm trying to add a test case but I haven't figured out how I can 'mock' a user session.  

Any idea?

**Comment by edewit** [comment]
Good point I have no idea... but does this really work though? Why is remove a 'GET' request?

**Comment by ogaston** [comment]
Sorry my bad, I already fixed it. it's a DELETE.

and Yes, it works. I just used the current request method and add a new endpoint `DELETE /{realm}/sessions/{session}` which can be found in the official REST API docs.

**Pull request merged**
