### PR TITLE
List users with role in realm

### PR DESCRIPTION
**Pull request by SergioCruzA**
Hello maintainers!

This PR adds support for role scopes.
We need the endpoint for get users in a role associated to a realm.

Looking forward for your feedback!

### CODE REVIEW

**Comment by zagaria** [comment]
@SergioCruzA looks good. Please update README.md file. Thanks!

**Comment by bacloud23** [comment]
This just does not work and has been merged. There is no such API on KEYCLOAK API
no such this as:
> (roleName) => `/roles/${roleName}/users`;

**Comment by jonkoops** [comment]
@bacloud23 if you could please file this as a new issue on [our repo.](https://github.com/keycloak/keycloak-ui/issues)

**Comment by bacloud23** [comment]
as soon as I can thanks @jonkoops 
but it just tried not work with latest keycloak API. there is no such endpoint

**Pull request merged**
