### PR TITLE
Refactor to allow custom `KeycloakAdmin` and `Agent`

### PR DESCRIPTION
**Pull request by rocketeerbkw**
For our use of this library we found it very buggy to rely on a global instance with a single `setTimeout` based method for refreshing the access token (which expires every minute). The errors we saw from this library were lots of 404 and 401 requests that would happen "randomly."

To fix this issue we changed the architecture so that every request gets a new instance and the instance itself checks if the token is expired before every request. In order to accomplish this we needed to extend the `Agent` class and inject that into the library. We also needed a way to store the credentials so that the `Agent` can have access to them.

This PR introduces changes that allow us to use a custom `KeycloakAdmin` class and a custom `Agent` class. You can see how we are doing this in our app at https://github.com/amazeeio/lagoon/pull/1386/files#diff-f71422e7ecb24f0ba83e261079b78d07

### CODE REVIEW

**Comment by rocketeerbkw** [comment]
I was not able to run the linter or tests, do you have docs for those?

```bash

➜  keycloak-admin git:(allow-more-customization) ✗ yarn lint
yarn run v1.17.3
$ tslint --force --format verbose "src/**/*.ts" "test/*"
ERROR: (no-console) test/clientScopes.spec.ts[445, 11]: Calls to 'console.log' are not allowed.
ERROR: (object-literal-key-quotes) test/clients.spec.ts[441, 11]: Unquoted property 'role' found.
ERROR: (quotemark) test/groupUser.spec.ts[51, 6]: " should be '
ERROR: (space-before-function-paren) test/realms.spec.ts[17, 28]: Spaces before function parens are disallowed
ERROR: (space-before-function-paren) test/realms.spec.ts[75, 36]: Spaces before function parens are disallowed
ERROR: (semicolon) test/roles.spec.ts[114, 5]: Missing semicolon
ERROR: (space-before-function-paren) test/users.spec.ts[27, 27]: Spaces before function parens are disallowed
ERROR: (space-before-function-paren) test/users.spec.ts[368, 37]: Spaces before function parens are disallowed
ERROR: (space-before-function-paren) test/users.spec.ts[447, 59]: Spaces before function parens are disallowed
ERROR: (quotemark) test/users.spec.ts[475, 8]: " should be '

✨  Done in 1.33s.
```

`yarn test`
```bash

1) Authorization
       should get token from local keycloak:
     Error: connect ECONNREFUSED 127.0.0.1:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
```

**Comment by rocketeerbkw** [comment]
ya, tests on travis failed. would be happy to fix with a little push in the right direction. I obviously need to run a local keycloak, but is there default data/accounts/realms that need to exist?

**Comment by zagaria** [comment]
Hello @rocketeerbkw. 

Yes. you need to run local Keycloak.

`docker run --name keycloak -d -p 127.0.0.1:8080:8080 -e KEYCLOAK_USER=wwwy3y3 -e KEYCLOAK_PASSWORD=wwwy3y3 jboss/keycloak:6.0.1`

No any default data, all information will be created and deleted when tests running.

**Comment by rocketeerbkw** [comment]
Fixed all the tests. Since we're using this in production I had to check the build artifacts in to git, but I can rebase and get a clean commit history if the changes are approved and it's requested.

**Comment by edewit** [comment]
@rocketeerbkw, I see what you did here externalized `Agent`, wouldn't it be a better idea to make it that the client sees that the token has expired and it will fetch a new one when it can? We could even make this behavior configurable.

**Comment by rocketeerbkw** [comment]
I'm open to collaborate on anything that will solve the issues stated in the description.

> the client sees that the token has expired and it will fetch a new one
Perhaps... but at the time of this PR that didn't feel like the correct abstraction level since the agent was responsible for handling all the HTTP requests. You could argue, and I could be convinced, that authentication errors should be handled at the client layer and not in the "transport" layer though.

Regardless of that discussion, this PR could still go in (with some more work on my part), unless you think it would never be desirable to allow users of this library to customize the `KeycloakAdmin` or `Agent` classes?

**Comment by edewit** [comment]
@rocketeerbkw refreshing the token with a setTimout is not a valid way to use this library in the first place. Seems to me refactoring the Agent out make the use of this library much more complicated. If you would need a long lasting connection with keycloak I would create an offline token then you wouldn't need the refresh token at all

**Pull request closed without merging**
